using Network.Core.Models;
using System;
using System.ComponentModel.DataAnnotations;

namespace Network.API.Model
{
    public class Speed_DataOkla : AuditEntity
    {
        [StringLength(255)]
        public string FileImport { get; set; }
        [StringLength(500)]public string id_result { get; set; }
        [StringLength(500)]public string guid_result { get; set; }
        [StringLength(500)]public string id_platform { get; set; }
        public DateTimeOffset? ts_result { get; set; }
        public DateTimeOffset? ts_result_received { get; set; }
        [StringLength(500)]public string attr_location_timezone { get; set; }
        [StringLength(500)]public string id_device { get; set; }
        [StringLength(500)]public string attr_device_android_fingerprint { get; set; }
        [StringLength(500)]public string attr_device_model { get; set; }
        [StringLength(500)]public string attr_device_manufacturer { get; set; }
        [StringLength(500)]public string attr_device_model_raw { get; set; }
        [StringLength(500)]public string attr_device_manufacturer_raw { get; set; }
        [StringLength(500)]public string attr_device_brand_raw { get; set; }
        [StringLength(500)]public string attr_device_chipset { get; set; }
        [StringLength(500)]public string attr_device_chipset_manufacturer { get; set; }
        [StringLength(500)]public string attr_device_hardware_name { get; set; }
        [StringLength(500)]public string attr_device_os_version { get; set; }
        [StringLength(500)]public string attr_device_build { get; set; }
        [StringLength(500)]public string is_device_rooted { get; set; }
        [StringLength(500)]public string attr_device_radio { get; set; }
        [StringLength(500)]public string attr_device_ram_mb { get; set; }
        [StringLength(500)]public string attr_device_storage_mb { get; set; }
        [StringLength(500)]public string is_device_world_phone { get; set; }
        [StringLength(500)]public string attr_device_multi_sim_support { get; set; }
        [StringLength(500)]public string num_device_active_modems { get; set; }
        [StringLength(500)]public string num_device_supported_modems { get; set; }
        [StringLength(500)]public string is_device_concurrent_voice_data_supported { get; set; }
        [StringLength(500)]public string is_device_data_connection_allowed { get; set; }
        [StringLength(500)]public string is_device_data_capable { get; set; }
        [StringLength(500)]public string is_device_data_roaming_enabled { get; set; }
        [StringLength(500)]public string is_device_icc_card_present { get; set; }
        [StringLength(500)]public string attr_device_service_state { get; set; }
        [StringLength(500)]public string attr_device_thermal_status { get; set; }
        [StringLength(500)]public string val_device_thermal_headroom { get; set; }
        [StringLength(500)]public string is_app_permission_phone_state { get; set; }
        [StringLength(500)]public string is_app_permission_fine_location { get; set; }
        [StringLength(500)]public string is_app_permission_coarse_location { get; set; }
        [StringLength(500)]public string is_app_permission_background_location { get; set; }
        [StringLength(500)]public string is_app_permission_wifi_state { get; set; }
        [StringLength(500)]public string attr_sim_operator_common_name { get; set; }
        [StringLength(500)]public string attr_sim_operator_name_raw { get; set; }
        [StringLength(500)]public string attr_sim_operator_mcc { get; set; }
        [StringLength(500)]public string attr_sim_operator_mnc { get; set; }
        [StringLength(500)]public string attr_altsim_operator_name { get; set; }
        [StringLength(500)]public string attr_altsim_operator_mcc { get; set; }
        [StringLength(500)]public string attr_altsim_operator_mnc { get; set; }
        [StringLength(500)]public string attr_network_operator_mcc { get; set; }
        [StringLength(500)]public string attr_network_operator_mnc { get; set; }
        [StringLength(500)]public string attr_network_operator_common_name { get; set; }
        [StringLength(500)]public string attr_isp_common_name { get; set; }
        [StringLength(500)]public string attr_isp_name_raw { get; set; }
        [StringLength(500)]public string attr_sim_type_allocation_code { get; set; }
        [StringLength(500)]public string attr_sim_state { get; set; }
        [StringLength(500)]public string attr_test_method { get; set; }
        [StringLength(500)]public string attr_test_ip_version { get; set; }
        [StringLength(500)]public string id_connection_type_start { get; set; }
        [StringLength(500)]public string id_connection_type_end { get; set; }
        [StringLength(500)]public string num_connections_failed { get; set; }
        [StringLength(500)]public string is_connection_carrier_aggregation { get; set; }
        [StringLength(500)]public string attr_connection_nr_state { get; set; }
        [StringLength(500)]public string attr_connection_apn { get; set; }
        [StringLength(500)]public string id_connection_net_speed { get; set; }
        [StringLength(500)]public string is_connection_access_technology_nr { get; set; }
        [StringLength(500)]public string id_connection_network_override_type { get; set; }
        [StringLength(500)]public string attr_connection_downstream_bandwidth_kbps { get; set; }
        [StringLength(500)]public string attr_connection_upstream_bandwidth_kbps { get; set; }
        [StringLength(500)]public string attr_connection_nat64_prefix { get; set; }
        [StringLength(500)]public string attr_location_latitude { get; set; }
        [StringLength(500)]public string attr_location_longitude { get; set; }
        [StringLength(500)]public string attr_location_start_latitude { get; set; }
        [StringLength(500)]public string attr_location_start_longitude { get; set; }
        [StringLength(500)]public string id_location_start_type { get; set; }
        [StringLength(500)]public string id_location_end_type { get; set; }
        [StringLength(500)]public string attr_location_accuracy_m { get; set; }
        [StringLength(500)]public string attr_location_age_ms { get; set; }
        [StringLength(500)]public string attr_location_altitude_m { get; set; }
        [StringLength(500)]public string attr_location_vertical_accuracy_m { get; set; }
        [StringLength(500)]public string attr_location_speed_mps { get; set; }
        [StringLength(500)]public string attr_place_formatted_address { get; set; }
        [StringLength(500)]public string attr_place_name { get; set; }
        [StringLength(500)]public string attr_place_locality_type { get; set; }
        [StringLength(500)]public string attr_place_country { get; set; }
        [StringLength(500)]public string attr_place_country_code { get; set; }
        [StringLength(500)]public string attr_place_region { get; set; }
        [StringLength(500)]public string attr_place_subregion { get; set; }
        [StringLength(500)]public string attr_place_subsubregion { get; set; }
        [StringLength(500)]public string attr_place_postal_code { get; set; }
        [StringLength(500)]public string num_packet_loss_sent { get; set; }
        [StringLength(500)]public string num_packet_loss_received { get; set; }
        [StringLength(500)]public string metric_packet_loss_percent { get; set; }
        [StringLength(500)]public string is_download_stopped { get; set; }
        [StringLength(500)]public string val_latency_min_ms { get; set; }
        [StringLength(500)]public string val_latency_iqm_ms { get; set; }
        [StringLength(500)]public string val_latency_max_ms { get; set; }
        [StringLength(500)]public string val_multiserver_latency_ms { get; set; }
        [StringLength(500)]public string val_download_latency_min_ms { get; set; }
        [StringLength(500)]public string val_download_latency_iqm_ms { get; set; }
        [StringLength(500)]public string val_download_latency_max_ms { get; set; }
        [StringLength(500)]public string val_upload_latency_min_ms { get; set; }
        [StringLength(500)]public string val_upload_latency_iqm_ms { get; set; }
        [StringLength(500)]public string val_upload_latency_max_ms { get; set; }
        [StringLength(500)]public string num_traceroute_hops { get; set; }
        [StringLength(500)]public string attr_traceroute0_ip_address { get; set; }
        [StringLength(500)]public string val_traceroute0_latency_ms { get; set; }
        [StringLength(500)]public string attr_traceroute1_ip_address { get; set; }
        [StringLength(500)]public string val_traceroute1_latency_ms { get; set; }
        [StringLength(500)]public string val_jitter_ms { get; set; }
        [StringLength(500)]public string val_multiserver_jitter_ms { get; set; }
        public int val_download_kbps { get; set; }
        [StringLength(500)]public string val_test_download_kb { get; set; }
        [StringLength(500)]public string num_test_download_threads { get; set; }
        [StringLength(500)]public string val_test_download_duration_ms { get; set; }
        public int val_upload_kbps { get; set; }
        [StringLength(500)]public string val_test_upload_kb { get; set; }
        [StringLength(500)]public string num_test_upload_threads { get; set; }
        [StringLength(500)]public string val_test_upload_duration_ms { get; set; }
        [StringLength(500)]public string attr_network_ipv4_address { get; set; }
        [StringLength(500)]public string attr_network_ipv6_address { get; set; }
        [StringLength(500)]public string attr_network_asn { get; set; }
        [StringLength(500)]public string attr_app_version { get; set; }
        [StringLength(500)]public string attr_app_store { get; set; }
        [StringLength(500)]public string attr_server_name { get; set; }
        [StringLength(500)]public string attr_server_sponsor_name { get; set; }
        [StringLength(500)]public string attr_server_latitude { get; set; }
        [StringLength(500)]public string attr_server_longitude { get; set; }
        [StringLength(500)]public string val_server_distance_km { get; set; }
        [StringLength(500)]public string attr_server_country { get; set; }
        [StringLength(500)]public string attr_server_country_code { get; set; }
        [StringLength(500)]public string is_server_auto_selected { get; set; }
        [StringLength(500)]public string is_server_on_network { get; set; }
        [StringLength(500)]public string attr_server_asn { get; set; }
        [StringLength(500)]public string num_server_download { get; set; }
        [StringLength(500)]public string val_signal_rsrp_dbm { get; set; }
        [StringLength(500)]public string val_signal_csi_rsrp_dbm { get; set; }
        [StringLength(500)]public string val_signal_ss_rsrp_dbm { get; set; }
        [StringLength(500)]public string val_signal_rsrq_db { get; set; }
        [StringLength(500)]public string val_signal_csi_rsrq_db { get; set; }
        [StringLength(500)]public string val_signal_ss_rsrq_db { get; set; }
        [StringLength(500)]public string val_signal_rssnr_db { get; set; }
        [StringLength(500)]public string val_signal_csi_snr_db { get; set; }
        [StringLength(500)]public string val_signal_ss_snr_db { get; set; }
        [StringLength(500)]public string val_signal_wcdma_ecno_db { get; set; }
        [StringLength(500)]public string val_signal_rssi_dbm { get; set; }
        [StringLength(500)]public string val_signal_gsm_rssi_dbm { get; set; }
        [StringLength(500)]public string val_signal_timing_advance_ts { get; set; }
        [StringLength(500)]public string val_signal_cqi { get; set; }
        [StringLength(500)]public string attr_cell_nr_frequency_range { get; set; }
        [StringLength(500)]public string attr_cell_bandwidth_khz { get; set; }
        [StringLength(500)]public string attr_cell_bandwidths_khz { get; set; }
        [StringLength(500)]public string id_cell_primary { get; set; }
        [StringLength(500)]public string id_cell_lte_enodeb { get; set; }
        [StringLength(500)]public string attr_cell_pci { get; set; }
        [StringLength(500)]public string attr_cell_nr_pci { get; set; }
        [StringLength(500)]public string attr_cell_tac { get; set; }
        [StringLength(500)]public string attr_cell_lac { get; set; }
        [StringLength(500)]public string attr_cell_psc { get; set; }
        [StringLength(500)]public string attr_cell_frequency_channel { get; set; }
        [StringLength(500)]public string attr_cell_frequency_channel_type { get; set; }
        [StringLength(500)]public string attr_cell_nr_arfcn { get; set; }
        [StringLength(500)]public string attr_cell_lte_bands { get; set; }
        [StringLength(500)]public string attr_cell_nr_bands { get; set; }
        [StringLength(500)]public string is_network_roaming { get; set; }
        [StringLength(500)]public string is_network_international_roaming { get; set; }
        [StringLength(500)]public string is_network_vpn { get; set; }
        [StringLength(500)]public string is_device_5g_capable { get; set; }
        [StringLength(500)]public string is_portal_included { get; set; }
        [StringLength(500)]public string attr_portal_categories { get; set; }
        [StringLength(500)]public string attr_connection_type_start_string { get; set; }
        [StringLength(500)]public string attr_connection_type_end_string { get; set; }
        [StringLength(500)]public string attr_device_esim_embedded { get; set; }
        [StringLength(500)]public string id_cell_nr { get; set; }
        [StringLength(500)]public string id_cell_start { get; set; }
        [StringLength(500)]public string attr_network_operator_mcc_nr { get; set; }
        [StringLength(500)]public string attr_network_operator_mnc_nr { get; set; }
    }
}
